### ISSUE TITLE
Encoders displaying opposite Polarity

### ISSUE THREAD

**Issue by les100** [cdemetriadis/Thrustmaster-T300-Steering-Wheel-Emulator#14]
Hi,
When rotating any of the encoders anticlockwise is displaying + and clockwise a -.What have i got wrong.I am a novice with Arduino sorry. 

Thanks
Les

**Comment by cdemetriadis** [comment]
Hey there Les,

So, as I’ve already mentioned this in a reply somewhere on the internets, you could save this with a software change. I cannot test this change currently as I’ve not a working version of the wheel/arduino. BUT, it should be fairly straight forward.

In the `t300_functions.ino` file, you will find the trigger for each of the Encoders. Line 36 and onward:

```
void encoderBB_decrement(i2cEncoderMiniLib* obj) {
 buttonValue = 1100;
}
void encoderBB_increment(i2cEncoderMiniLib* obj) {
 buttonValue = 1000;
}
void encoderABS_decrement(i2cEncoderMiniLib* obj) {
 buttonValue = 3000;
}
void encoderABS_increment(i2cEncoderMiniLib* obj) {
 buttonValue = 3100;
}
void encoderTC_decrement(i2cEncoderMiniLib* obj) {
 buttonValue = 2000;
}
void encoderTC_increment(i2cEncoderMiniLib* obj) {
 buttonValue = 2100;
}
```

To swap the -/+ actions, you’d probably only need to change the buttonValue for each. As an example, in this case, your code should become:

```
void encoderBB_decrement(i2cEncoderMiniLib* obj) {
 buttonValue = 1000;
}
void encoderBB_increment(i2cEncoderMiniLib* obj) {
 buttonValue = 1100;
}
void encoderABS_decrement(i2cEncoderMiniLib* obj) {
 buttonValue = 3100;
}
void encoderABS_increment(i2cEncoderMiniLib* obj) {
 buttonValue = 3000;
}
void encoderTC_decrement(i2cEncoderMiniLib* obj) {
 buttonValue = 2100;
}
void encoderTC_increment(i2cEncoderMiniLib* obj) {
 buttonValue = 2000;
}
```

But again, please forgive me as I cannot double check and test the above.

Trust me when I say that all of the code you see was initially trial and error for me as well ;)

Best of luck buddy!
