### ISSUE TITLE
Clean Thrustmaster F1 code

### ISSUE THREAD

**Issue by miniraziel** [cdemetriadis/Thrustmaster-T300-Steering-Wheel-Emulator#15]
Hi, i've seen you fantastic job about this project a few time ago, i've made myself too a few wheels using T300RS emulation and also a work in progress with T-GT emulation(thanks to Taras for his work), i would like to ask you if it is possible for you to publish the code to emulate the Thrustmaster F1 wheel(the one you used for this project), but in a clean version. I mean without screen controls and in the original buttons form(like the original F1 wheel: 18 buttons and 2 encoders). I've already try to contact Bremme on thingiverse for the original code but i didn't gen answer... and Taras told me that he don't have the time to work anymore on these projects.
I'm not a programmer and except for a few buttons reordering i'm not able to modify your sketch or the bremme's one.
Thank you very much
Best regards
Roberto

**Comment by miniraziel** [comment]
Wrong position, not an issue but a request.
sorry

**Comment by cdemetriadis** [comment]
Hey @miniraziel, unfortunately I only provide this as is. I've since moved onto other platforms, so even if I did have the time to edit it, I would not be able to test it.

Please, feel free to use it as you see fit. Maybe have a friend to help you out?
