### ISSUE TITLE
Buttons are not constant

### ISSUE THREAD

**Issue by Shane87F3Ng** [cdemetriadis/Thrustmaster-T300-Steering-Wheel-Emulator#9]
First of all, thanks for the amazing work,

I realized, that Buttons are not constant pressed but flicker a lot. I do not use a rtc nor a display, just 3 encoders as you and some buttons. Therefore I modified the code, but it also happens with the original one. If i keep the button pushed, it is like i would very very very frequently push it. Any chance to look into it or does it happen because i do not use RTC, nor buzzer or reset? I use it on a TS-PC.

Best Regards!

**Comment by cdemetriadis** [comment]
Try playing with the DEBOUNCE number. Currently it is on 90, but you could try raising it.

**Comment by Shane87F3Ng** [comment]
That did IT! Thank you so much!

A general question, so you work on the advanced mode?

**Comment by cdemetriadis** [comment]
> A general question, so you work on the advanced mode?

Not quite sure I understand.

**Comment by Shane87F3Ng** [comment]
In the description, you said, that the advanced mode for PC is not yet working. So my question was, If you are still looking into that or if it was just a note :)

**Comment by cdemetriadis** [comment]
Oh, that's just a note. I do not use a PC for gaming, so cannot test it.

I'm assuming the transition wouldn't be too hard though.

**Comment by cdemetriadis** [comment]
Hey @Shane87F3Ng, I've added a new branch that works with the PC Advanced mode. Check it out here https://github.com/cdemetriadis/Thrustmaster-T300-Steering-Wheel-Emulator/tree/PC-Advanced-Mode

**Comment by Shane87F3Ng** [comment]
Thanks for the Info! I will try it and see, if can use more buttons :)

**Comment by cdemetriadis** [comment]
@Shane87F3Ng You can find the PC bindings here https://github.com/cdemetriadis/Thrustmaster-T300-Steering-Wheel-Emulator/blob/PC-Advanced-Mode/control-bindings.md
